name: Flutter iOS Build

on:
  push:
    branches: [main]
  workflow_dispatch:   # bisa juga dijalankan manual

jobs:
  build-ios:
    runs-on: macos-latest  # penting! macOS runner

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.0"

      - run: flutter pub get

      - name: Build iOS app
        run: flutter build ios --release

      - name: Build IPA
        run: flutter build ipa

      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/ipa/*.ipa
